version: '3.8'
services:

  app:
    image: weather_app
    depends_on:
      - postgres
    ports:
      - 5000:5000
    volumes:
      - .env:/app/.env

  postgres:
    image: postgres:17.5
    restart: always
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - 5433:5432
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: